#pragma once
// Development-only tracing for the oracle interpreter.
//
// Nothing here is ever linked into the shipped game, and nothing here is on unless a tool switches
// it on: a null `Cpu::tracer` costs one predictable branch per COP2 instruction and per memory
// access.
//
// Three streams, because tracing a frame of the original needs three kinds of evidence:
//
//   * COP2  - every GTE command with the FULL register file before and after it. That is a
//             (inputs, opcode) -> (outputs) triple, i.e. a replayable test vector generated by the
//             game's own code rather than by us.
//   * GPU   - every word that reaches the GPU, whether the CPU stored it into GP0/GP1 directly or
//             DMA channel 2 fed it from a linked list. Each word carries the guest pc (CPU stores)
//             or the guest RAM address it came from (DMA), which is what makes "this byte of this
//             .GEO became this GPU word" provable.
//   * memory- watchpoints: reads and writes inside named address ranges, with the pc. This is the
//             "who reads DOD3+0x14" instrument.
#include <cstdint>
#include <string>
#include <vector>

namespace rr::interp {

struct Cop2Record {
    uint64_t seq = 0;          // Cpu::instructionsRetired when the command issued
    uint32_t pc = 0;           // the address of the COP2 instruction
    uint32_t instruction = 0;  // the full 32-bit command word (opcode, sf, lm, MVMVA selects)
    uint32_t inDr[32]{};       // cop2r0..31 before
    uint32_t inCr[32]{};       // cop2r32..63 before
    uint32_t outDr[32]{};      // cop2r0..31 after
    uint32_t outFlag = 0;      // cop2r63 after
};

enum class GpuWordSource : uint8_t {
    CpuStore = 0,   // sw / sh into GP0 or GP1
    DmaLinkedList = 1,
    DmaBlock = 2,
};

struct GpuWord {
    uint64_t seq = 0;
    uint32_t pc = 0;        // issuing instruction (CPU stores only; 0 for DMA)
    uint32_t value = 0;
    uint32_t address = 0;   // guest RAM address the word was fetched from (DMA only)
    uint8_t port = 0;       // 0 = GP0, 1 = GP1
    GpuWordSource source = GpuWordSource::CpuStore;
};

struct MemEvent {
    uint64_t seq = 0;
    uint32_t pc = 0;
    uint32_t address = 0;
    uint32_t value = 0;
    uint8_t size = 0;      // 1 / 2 / 4
    uint8_t isWrite = 0;
    uint16_t watchIndex = 0;
};

struct CallEvent {
    uint64_t seq = 0;
    uint32_t from = 0;
    uint32_t target = 0;
    uint32_t args[4]{};
    // The caller's stack pointer at the moment of the `jal`/`jalr`. Without it a call tree has to be
    // guessed from a static call graph, which breaks on every `jalr` and on every function whose
    // entry the heuristic missed; with it the nesting is exact, because a callee's sp is always
    // lower than its caller's.
    uint32_t sp = 0;
};

// A pc probe: whenever execution reaches `pc`, the whole integer register file is recorded. This is
// the instrument that turns "some code reads this field" into "this instruction, with these
// operands, produced this value".
struct ProbeHit {
    uint64_t seq = 0;
    uint32_t pc = 0;
    uint32_t regs[32]{};
    uint32_t hi = 0, lo = 0;
};

struct Watch {
    uint32_t low = 0;   // inclusive, virtual address as the guest uses it (mirrors are normalised)
    uint32_t high = 0;  // inclusive
    std::string name;
    bool onRead = true;
    bool onWrite = true;
    uint64_t readHits = 0;
    uint64_t writeHits = 0;
};

class Tracer {
public:
    Tracer();

    // --- switches. All default to off; a tool turns on exactly what it wants.
    bool traceCop2 = false;
    bool traceGpu = false;
    bool traceCalls = false;

    // Caps, so a runaway run cannot eat all host memory. Recording stops (and `*Truncated` is set)
    // rather than the run being aborted - a partial trace is still evidence.
    size_t maxCop2 = 4u * 1000u * 1000u;
    size_t maxGpu = 8u * 1000u * 1000u;
    size_t maxMem = 4u * 1000u * 1000u;
    size_t maxCalls = 4u * 1000u * 1000u;

    bool cop2Truncated = false;
    bool gpuTruncated = false;
    bool memTruncated = false;
    bool callsTruncated = false;

    size_t maxProbeHits = 2u * 1000u * 1000u;
    bool probesTruncated = false;

    std::vector<Cop2Record> cop2;
    std::vector<GpuWord> gpu;
    std::vector<MemEvent> mem;
    std::vector<CallEvent> calls;
    std::vector<Watch> watches;
    std::vector<ProbeHit> probeHits;
    std::vector<std::pair<uint32_t, std::string>> probes;

    // Counts that keep going even after the corresponding vector is capped.
    uint64_t cop2Count = 0;
    uint64_t gpuWordCount = 0;

    void AddWatch(uint32_t address, uint32_t length, std::string name, bool onRead = true,
                  bool onWrite = true);
    bool hasWatches() const { return !watches.empty(); }

    // `address` is the raw guest address; KUSEG/KSEG0/KSEG1 all normalise to the KSEG0 form so a
    // watch set on 0x801A0000 also fires for an access through 0x001A0000.
    //
    // Hot path: one bitmap probe per byte-range word. The linear pass over the named ranges only
    // runs on a hit, so thousands of watches cost the same as one.
    inline bool MayWatch(uint32_t address) const {
        const uint32_t phys = address & 0x1FFFFFFFu;
        if (phys >= 0x00800000u) return true; // outside RAM: fall back to the slow path
        const uint32_t word = (phys & 0x001FFFFFu) >> 2;
        return (watchBitmap_[word >> 6] & (uint64_t{1} << (word & 63))) != 0;
    }
    void OnMemory(uint64_t seq, uint32_t pc, uint32_t address, uint32_t size, uint32_t value,
                  bool isWrite);

    void AddProbe(uint32_t pc, std::string name);
    bool hasProbes() const { return !probes.empty(); }
    inline bool MayProbe(uint32_t pc) const {
        const uint32_t phys = pc & 0x1FFFFFFFu;
        if (phys >= 0x00800000u) return false;
        const uint32_t word = (phys & 0x001FFFFFu) >> 2;
        return (probeBitmap_[word >> 6] & (uint64_t{1} << (word & 63))) != 0;
    }
    void OnProbe(uint64_t seq, uint32_t pc, const uint32_t* regs, uint32_t hi, uint32_t lo);

    void Clear();

private:
    std::vector<uint64_t> watchBitmap_;
    std::vector<uint64_t> probeBitmap_;
};

} // namespace rr::interp
