# The VR hands (tools/rrgame/vr_hands_draw.h): third_party/vrhands (UltimateXR MIT meshes, the albedo)
# embedded into rrgame - and so into the Quest's librrgame.so, which is built from rrgame's source list
# (cmake/vr.cmake) - as byte arrays in a generated vr_hand_assets.cpp, as the gt2-play project does
# (its cmake/vr-hand-assets.cmake). No data file to install next to the game or on the headset.
set(RR_HAND_ASSETS BigHandLeft.uxrh BigHandRight.uxrh BigHandsAlbedo.png)
set(RR_HAND_CPP "${CMAKE_CURRENT_BINARY_DIR}/vr_hand_assets.cpp")
set(rr_hand_text "// Generated by cmake/vr-hand-assets.cmake from third_party/vrhands - do not edit.\n")
string(APPEND rr_hand_text "#include <cstdint>\n#include <span>\nnamespace rrgame {\nnamespace {\n")
foreach(asset ${RR_HAND_ASSETS})
    set(path "${CMAKE_CURRENT_SOURCE_DIR}/third_party/vrhands/${asset}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    string(MAKE_C_IDENTIFIER "${asset}" symbol)
    file(READ "${path}" bytes HEX)
    # 32 bytes a line (a compiler's line length stays small), each byte as 0xNN,
    string(REGEX REPLACE "([0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f])"
           "\\1\n" bytes "${bytes}")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${bytes}")
    string(APPEND rr_hand_text "const uint8_t ${symbol}[] = {\n${bytes}};\n")
endforeach()
string(APPEND rr_hand_text "} // namespace\n"
       "// 0 the left hand's mesh, 1 the right hand's, 2 the albedo PNG (vr_hands_draw.h VrHandAsset).\n"
       "std::span<const uint8_t> VrHandAsset(int index) {\n"
       "    if (index == 0) return BigHandLeft_uxrh;\n"
       "    if (index == 1) return BigHandRight_uxrh;\n"
       "    return BigHandsAlbedo_png;\n"
       "}\n} // namespace rrgame\n")
file(CONFIGURE OUTPUT "${RR_HAND_CPP}" CONTENT "${rr_hand_text}" @ONLY)
target_sources(rrgame PRIVATE "${RR_HAND_CPP}")
